let words = `
poplewas added by chained_bear and appears on 6 lists
caromwas added by chained_bear and appears on 61 lists
ergotwas added by chained_bear and appears on 25 lists
zibebwas added by chained_bear and appears on 2 lists
agletwas added by chained_bear and appears on 82 lists
cubebwas added by chained_bear and appears on 13 lists
nerpawas added by chained_bear and appears on 3 lists
talerwas added by chained_bear and appears on 3 lists
qitrawas added by chained_bear and appears on 3 lists
swainwas added by chained_bear and appears on 48 lists
oxterwas added by chained_bear and appears on 41 lists
panicwas added by chained_bear and appears on 54 lists
kvasswas added by chained_bear and appears on 13 lists
karstwas added by chained_bear and appears on 31 lists
stropwas added by chained_bear and appears on 36 lists
skirrwas added by chained_bear and appears on 17 lists
mittswas added by chained_bear and appears on 4 lists
mucidwas added by chained_bear and appears on 9 lists
knobswas added by chained_bear and appears on 6 lists
vapidwas added by chained_bear and appears on 282 lists
vistawas added by chained_bear and appears on 43 lists
karstwas added by chained_bear and appears on 31 lists
hyraxwas added by chained_bear and appears on 28 lists
spruewas added by chained_bear and appears on 13 lists
okapiwas added by chained_bear and appears on 30 lists
prongwas added by chained_bear and appears on 21 lists
venomwas added by chained_bear and appears on 44 lists
anurawas added by chained_bear and appears on 3 lists
felidwas added by chained_bear and appears on 14 lists
minmiwas added by chained_bear and appears on 3 lists
cycadwas added by chained_bear and appears on 13 lists
cladewas added by chained_bear and appears on 24 lists
wlonkwas added by chained_bear and appears on 3 lists
druzewas added by chained_bear and appears on 5 lists
taborwas added by chained_bear and appears on 12 lists
craicwas added by chained_bear and appears on 17 lists
skelpwas added by chained_bear and appears on 12 lists
skelfwas added by chained_bear and appears on 14 lists
äijiäwas added by chained_bear and appears on 4 lists
gleekwas added by chained_bear and appears on 32 lists
vervewas added by chained_bear and appears on 90 lists
cavilwas added by chained_bear and appears on 178 lists
rixlewas added by chained_bear and appears on 5 lists
civetwas added by chained_bear and appears on 38 lists
macawwas added by chained_bear and appears on 16 lists
shardwas added by chained_bear and appears on 72 lists
sloomwas added by chained_bear and appears on 13 lists
squirwas added by chained_bear and appears on 11 lists
freamwas added by chained_bear and appears on 13 lists
merlewas added by chained_bear and appears on 18 lists
arraswas added by chained_bear and appears on 39 lists
scurfwas added by chained_bear and appears on 32 lists
troatwas added by chained_bear and appears on 12 lists
kedgewas added by chained_bear and appears on 24 lists
surahwas added by chained_bear and appears on 12 lists
positwas added by chained_bear and appears on 114 lists
nacrewas added by chained_bear and appears on 73 lists
slakewas added by chained_bear and appears on 145 lists
swardwas added by chained_bear and appears on 52 lists
shtupwas added by chained_bear and appears on 12 lists
splaywas added by chained_bear and appears on 45 lists
vulvawas added by chained_bear and appears on 36 lists
piquewas added by chained_bear and appears on 212 lists
lymphwas added by chained_bear and appears on 14 lists
kioskwas added by chained_bear and appears on 41 lists
gnurrwas added by chained_bear and appears on 6 lists
drollwas added by chained_bear and appears on 148 lists
vaguewas added by chained_bear and appears on 72 lists
xebecwas added by chained_bear and appears on 32 lists
giguewas added by chained_bear and appears on 16 lists
whelpwas added by chained_bear and appears on 59 lists
sprogwas added by chained_bear and appears on 19 lists
scrimwas added by chained_bear and appears on 37 lists
imbuewas added by chained_bear and appears on 117 lists
snoodwas added by chained_bear and appears on 77 lists
aegiswas added by chained_bear and appears on 149 lists
squeewas added by chained_bear and appears on 42 lists
skirlwas added by chained_bear and appears on 35 lists
skunkwas added by chained_bear and appears on 46 lists
pronkwas added by chained_bear and appears on 52 lists
gnomewas added by chained_bear and appears on 73 lists
savvywas added by chained_bear and appears on 84 lists
snarfwas added by chained_bear and appears on 35 lists
yachtwas added by chained_bear and appears on 37 lists
fetidwas added by chained_bear and appears on 153 lists
schwawas added by chained_bear and appears on 49 lists
lithewas added by chained_bear and appears on 279 lists
shoatwas added by chained_bear and appears on 23 lists
mulctwas added by chained_bear and appears on 119 lists
cruetwas added by chained_bear and appears on 27 lists
abaftwas added by chained_bear and appears on 39 lists
lividwas added by chained_bear and appears on 137 lists
angstwas added by chained_bear and appears on 115 lists
feralwas added by chained_bear and appears on 127 lists
flankwas added by chained_bear and appears on 52 lists
blingwas added by chained_bear and appears on 39 lists
quipuwas added by chained_bear and appears on 19 lists
blimpwas added by chained_bear and appears on 36 lists
plotzwas added by chained_bear and appears on 23 lists
lucrewas added by chained_bear and appears on 74 lists
duchywas added by chained_bear and appears on 23 lists
calyxwas added by chained_bear and appears on 50 lists
nanuqwas added by chained_bear and appears on 3 lists
flewswas added by chained_bear and appears on 13 lists
imeruwas added by chained_bear and appears on 2 lists
magmawas added by chained_bear and appears on 52 lists
smitewas added by chained_bear and appears on 72 lists
flapswas added by chained_bear and appears on 11 lists
ninjawas added by chained_bear and appears on 85 lists
ochrewas added by chained_bear and appears on 106 lists
divvywas added by chained_bear and appears on 36 lists
thirlwas added by chained_bear and appears on 13 lists
ingotwas added by chained_bear and appears on 36 lists
igloowas added by chained_bear and appears on 36 lists
nadirwas added by chained_bear and appears on 267 lists
pixiewas added by chained_bear and appears on 49 lists
druidwas added by chained_bear and appears on 35 lists
idyllwas added by chained_bear and appears on 67 lists
pithywas added by chained_bear and appears on 247 lists
swoonwas added by chained_bear and appears on 64 lists
positwas added by chained_bear and appears on 114 lists
roguewas added by chained_bear and appears on 136 lists
queenwas added by chained_bear and appears on 76 lists
piquewas added by chained_bear and appears on 212 lists
feverwas added by chained_bear and appears on 33 lists
poppywas added by chained_bear and appears on 53 lists
saucywas added by chained_bear and appears on 74 lists
quirtwas added by chained_bear and appears on 31 lists
eludewas added by chained_bear and appears on 77 lists
sneerwas added by chained_bear and appears on 49 lists
mochawas added by chained_bear and appears on 46 lists
satyrwas added by chained_bear and appears on 80 lists
thrumwas added by chained_bear and appears on 51 lists
umberwas added by chained_bear and appears on 83 lists
skeinwas added by chained_bear and appears on 85 lists
swirlwas added by chained_bear and appears on 38 lists
rebarwas added by chained_bear and appears on 15 lists
vapidwas added by chained_bear and appears on 282 lists
uvulawas added by chained_bear and appears on 53 lists
xylemwas added by chained_bear and appears on 38 lists
ivorywas added by chained_bear and appears on 98 lists
oomphwas added by chained_bear and appears on 40 lists
plushwas added by chained_bear and appears on 38 lists
kazoowas added by chained_bear and appears on 22 lists
meleewas added by chained_bear and appears on 88 lists
bingewas added by chained_bear and appears on 37 lists
epochwas added by chained_bear and appears on 96 lists
cacaowas added by chained_bear and appears on 32 lists
acornwas added by chained_bear and appears on 51 lists
anvilwas added by chained_bear and appears on 42 lists
avastwas added by chained_bear and appears on 52 lists
equipwas added by chained_bear and appears on 19 lists
boluswas added by chained_bear and appears on 52 lists
cocoawas added by chained_bear and appears on 49 lists
curlywas added by chained_bear and appears on 17 lists
gelidwas added by chained_bear and appears on 106 lists
grebewas added by chained_bear and appears on 29 lists
navvywas added by chained_bear and appears on 24 lists
unagiwas added by chained_bear and appears on 10 lists
ogglewas added by chained_bear and appears on 3 lists
hordewas added by chained_bear and appears on 45 lists
bimbowas added by chained_bear and appears on 29 lists
lemonwas added by chained_bear and appears on 97 lists
thighwas added by chained_bear and appears on 20 lists
poundwas added by chained_bear and appears on 45 lists
knurlwas added by chained_bear and appears on 25 lists
maplewas added by chained_bear and appears on 58 lists
onionwas added by chained_bear and appears on 43 lists
grasswas added by chained_bear and appears on 66 lists
poingwas added by chained_bear and appears on 6 lists
clovewas added by chained_bear and appears on 48 lists
gumbowas added by chained_bear and appears on 33 lists
pulsewas added by chained_bear and appears on 56 lists
arrowwas added by chained_bear and appears on 36 lists
slingwas added by chained_bear and appears on 26 lists
whaupwas added by chained_bear and appears on 6 lists
guanowas added by chained_bear and appears on 29 lists
thripwas added by chained_bear and appears on 10 lists
tildewas added by chained_bear and appears on 29 lists
myrrhwas added by chained_bear and appears on 94 lists
puppywas added by chained_bear and appears on 37 lists
thumbwas added by chained_bear and appears on 30 lists
wharfwas added by chained_bear and appears on 36 lists
whalewas added by chained_bear and appears on 50 lists
squabwas added by chained_bear and appears on 46 lists
viperwas added by chained_bear and appears on 49 lists
easelwas added by chained_bear and appears on 21 lists
strumwas added by chained_bear and appears on 12 lists
crownwas added by chained_bear and appears on 63 lists
queerwas added by chained_bear and appears on 102 lists
sabrewas added by chained_bear and appears on 31 lists
pistewas added by chained_bear and appears on 24 lists
basilwas added by chained_bear and appears on 56 lists
anisewas added by chained_bear and appears on 39 lists
sumacwas added by chained_bear and appears on 31 lists
thymewas added by chained_bear and appears on 59 lists
sablewas added by chained_bear and appears on 94 lists
armorwas added by chained_bear and appears on 26 lists
azurewas added by chained_bear and appears on 212 lists
guleswas added by chained_bear and appears on 32 lists
oxbowwas added by chained_bear and appears on 21 lists
opiumwas added by chained_bear and appears on 41 lists
gleetwas added by chained_bear and appears on 25 lists
llamawas added by chained_bear and appears on 67 lists
lemurwas added by chained_bear and appears on 32 lists
stoatwas added by chained_bear and appears on 28 lists
coralwas added by chained_bear and appears on 87 lists
hyenawas added by chained_bear and appears on 23 lists
pandawas added by chained_bear and appears on 47 lists
skinkwas added by chained_bear and appears on 28 lists
horsewas added by chained_bear and appears on 66 lists
spoonwas added by chained_bear and appears on 85 lists
olivewas added by chained_bear and appears on 95 lists
caperwas added by chained_bear and appears on 82 lists
mangowas added by chained_bear and appears on 51 lists
baconwas added by chained_bear and appears on 62 lists
ramenwas added by chained_bear and appears on 23 lists
enokiwas added by chained_bear and appears on 8 lists
pizzawas added by chained_bear and appears on 67 lists
squidwas added by chained_bear and appears on 70 lists
sushiwas added by chained_bear and appears on 48 lists
spratwas added by chained_bear and appears on 16 lists
smeltwas added by chained_bear and appears on 47 lists
stropwas added by chained_bear and appears on 36 lists
bawdywas added by chained_bear and appears on 90 lists
hydrawas added by chained_bear and appears on 45 lists
eyriewas added by chained_bear and appears on 34 lists
phloxwas added by chained_bear and appears on 38 lists
fuguewas added by chained_bear and appears on 87 lists
lapiswas added by chained_bear and appears on 38 lists
aspicwas added by chained_bear and appears on 51 lists
veldtwas added by chained_bear and appears on 45 lists
pansywas added by chained_bear and appears on 53 lists
freakwas added by chained_bear and appears on 43 lists
twerpwas added by chained_bear and appears on 36 lists
fruitwas added by chained_bear and appears on 54 lists
elbowwas added by chained_bear and appears on 47 lists
bowelwas added by chained_bear and appears on 21 lists
skulkwas added by chained_bear and appears on 94 lists
spasmwas added by chained_bear and appears on 32 lists
queefwas added by chained_bear and appears on 26 lists
chunkwas added by chained_bear and appears on 32 lists
beefywas added by chained_bear and appears on 24 lists
schwawas added by chained_bear and appears on 49 lists
sambawas added by chained_bear and appears on 27 lists
barfywas added by chained_bear and appears on 4 lists
ennuiwas added by chained_bear and appears on 468 lists
`

words = words.split('\n')

words = words.map((word) => {
  let line = word.split(' ')
  let all = line[0].split('')
  let final = all[0] + all[1] + all[2] + all[3] + all[4]
  return final
})
console.log(JSON.stringify(words))
